; last modified 1 April 2001 by John Doe
[board]
pcbaPn = 5083554
pcbaRev = C.01
asyPn = 5083561
asyRev = C.10
asyRevNew = C.11
cutOffDateCode = RA2407

[pic]
rev = 1.1
path = C:\3500000_TetraProdSW\release\5084606_TetraPicPmic.X.production.ced45764R1.1.hex
tool = PK4
part = 24FJ256GA704

[fpga]
rev = 2.2.8
hwrev = 5
path = C:\3500000_TetraProdSW\utils\prog_flash.tcl
file = C:/3500000_TetraProdSW/release/am_top-20221212_FWA587R2.2.1_SW1A16R2.2.8.mcs

[Config]
port = COM6
SNdigitlength = 4
[scanner]
port = COM12

[config_power_supply]
port = GPIB0::5::INSTR
voltage = 18.5
min_voltage = 18.4
max_voltage = 18.6
current = 1.0

min_current_prePic = 0.005
max_current_prePic = 0.6

min_current_preFPGA = 0.1
max_current_preFPGA = 0.6

min_current_Final = 0.4
max_current_Final = 0.6

[burnin_power_supply]
port = GPIB0::5::INSTR
voltage = 19
current = 2
OVolt = 20

[burnin]
duration = 24:00:00
poll_interval = 00:20
min_current_mA = 100


BiB1 = COM46
BiB1port1 = COM18
BiB1port2 = COM16
BiB1port3 = COM17
BiB1port4 = COM15
BiB1port5 = COM13
BiB1port6 = COM12
BiB1port7 = COM20
BiB1port8 = COM19
BiB1port9 = COM14
BiB1port10 = COM9
BiB1port11 = COM10
BiB1port12 = COM11

BiB2 = COM47
BiB2port1 = COM31
BiB2port2 = COM26
BiB2port3 = COM30
BiB2port4 = COM29
BiB2port5 = COM27
BiB2port6 = COM28
BiB2port7 = COM6
BiB2port8 = COM23
BiB2port9 = COM21
BiB2port10 = COM24
BiB2port11 = COM22
BiB2port12 = COM25

BiB3 = COM48
BiB3port1 = COM33
BiB3port2 = COM49
BiB3port3 = COM50
BiB3port4 = COM44
BiB3port5 = COM45
BiB3port6 = COM40
BiB3port7 = COM34
BiB3port8 = COM53
BiB3port9 = COM52
BiB3port10 = COM38
BiB3port11 = COM51
BiB3port12 = COM35

BiB4 = COM55
BiB4port1 = COM56
BiB4port2 = COM57
BiB4port3 = COM32
BiB4port4 = COM43
BiB4port5 = COM42
BiB4port6 = COM37
BiB4port7 = COM41
BiB4port8 = COM58
BiB4port9 = COM36
BiB4port10 = COM59
BiB4port11 = COM60
BiB4port12 = COM61




[database]
; use IP address in case network name resolution is not working
server = 127.0.0.1
user = Glen
technicians = tetra_technicians
config = tetra_configuration
assembly = tetra_assemblies
burnin = tetra_burn_in
test = tetra_module_test
qc = tetra_final_inspection
local_folder = ../../local
remote_folder = C:\SynologyDrive

[rdiv_limits] ; low mA, high mA, low mV, high mV
sw3p6 = 431,555,3240,3780
sw5p5 = 107,138,4950,5775
sw2p8a = 242,350,2660,2940
sw2p8b = 164,248,2660,2940
sw2p4 = 1013,1304,2160,2520
sw1p4 = 945,1217,1260,1470

[rdv_limits] ; low mV, high mV
isu18p5 = 17575,19425
core1p0 = 950,1050
xvr1p0 = 950,1050
dig1p8 = 1710,1890
dig3p3 = 3135,3465
xvr1p2 = 1140,1260
div5p0 = 4750,5250
vdd3p3 = 3135,3465
rx2p5 = 2375,2625
tx2p5 = 2375,2625
adc1p8 = 1710,1890
